# Generated by Django 5.2.5 on 2025-09-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserS',
        ),
    ]
